name: Project Automation

on:
  issues:
    types:
      - opened
      - closed

jobs:
  update_project:
    runs-on: ubuntu-latest
    steps:
      - name: ì´ìŠˆ ìƒì„± ì‹œ í”„ë¡œì íŠ¸ ë³´ë“œì— ì¶”ê°€
        if: github.event.action == 'opened'
        uses: actions/add-to-project@v1
        with:
          project-url: "https://github.com/orgs/ESTSOFT-iOS-01/projects/6"
          github-token: ${{ secrets.PAT_TOKEN }}

      - name: ğŸ·ï¸ ì´ìŠˆ ìƒì„± ì‹œ `startDate` ì„¤ì •
        if: github.event.action == 'opened'
        uses: actions/update-project-fields@v1
        with:
          project-url: "https://github.com/orgs/ESTSOFT-iOS-01/projects/6"
          github-token: ${{ secrets.PAT_TOKEN }}
          field-name: "startDate"
          field-value: "${{ github.event.issue.created_at }}"

      - name: âœ… ì´ìŠˆ ë‹«í ë•Œ `endDate` ì„¤ì •
        if: github.event.action == 'closed'
        uses: actions/update-project-fields@v1
        with:
          project-url: "https://github.com/orgs/ESTSOFT-iOS-01/projects/6"
          github-token: ${{ secrets.PAT_TOKEN }}
          field-name: "endDate"
          field-value: "${{ github.event.issue.closed_at }}"
